[theme]
base="light"
primaryColor="#008080"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
baseRadius="10px"
buttonRadius="10px"

[theme.sidebar]
backgroundColor="#008080"
textColor="#FFFFFF"
primaryColor="#FFFFFF"
baseRadius="10px"
